on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: pnpm/action-setup@v6.0.3
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: 24.15.0
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm build:api
